title: Clear Typography
description: BY ROISIN CLEAR
footer_text: Copyright 2021 Roisin Clear
header_feature_image: ../uploads/photo-1516179257071-71a54dbb4853.jpeg
header_text: Clear Typography
header_text_color: "#ffffff"
bannerheight: 40vmax
navbarheight: 35px
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: true
fixednavbar: false
upzoom: true
items:
  - siteurl: https://www.clearcontent.online/
    name: "Clear Content Blog "
    tab: true
