title: Clear Typography
description: BY ROISIN CLEAR
footer_text: Copyright 2021 Roisin Clear
header_feature_image: ../uploads/new-project-3-.png
header_text: ""
header_text_color: "#ffffff"
bannerheight: 10vmax
navbarheight: 35px
logo: ../uploads/logo.jpg
favicon: ../uploads/favicon.ico
gridlayout: true
fixednavbar: false
upzoom: true
items:
  - siteurl: /aboutme/
    name: "About me "
    tab: true
